version: '3'

services:
  db:
    image: postgres:9.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: my-db
    volumes:
      - ./data/db:/data/db
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
